version: '3.6'
services:
  db:
    image: postgres:14
    restart: always
    volumes:
      - ${DB_DATA_PATH}:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}


  nest-app:
    depends_on:
      - db
    build:
      context: ./nest-app
    restart: always
    env_file:
      - .env
    ports:
      - ${NEST_PORT}:${NEST_PORT}

