version: '3.6'
services:
  db:
    image: postgres:14
    restart: always
    volumes:
      - ${DB_DATA_PATH}:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}

  nest-app:
    depends_on:
      - db
    build:
      context: ./nest-app
    restart: always
    env_file:
      - .env
    ports:
      - 4000:4000
    
  colyseus:
    depends_on:
      - nest-app
    image:  lambrohan/mygame:latest
    restart: always
    ports:
      - 2567:2567
    env_file:
      - .env
    environment:
      NODE_ENV: ${NODE_ENV}
      API_BACKEND_URL: http://nest-app:4000
      API_AUTH_TOKEN: ${API_AUTH_TOKEN}


